### ISSUE TITLE
Can't find FaceSwap anymore, what happend? [bug] 

### ISSUE THREAD

**Issue by HenryFroio** [melMass/comfy_mtb#128]
### Describe the bug

Well, the title is self explanatory

![Captura de tela 2023-11-20 175340](https://github.com/melMass/comfy_mtb/assets/94875647/90dd1e33-c492-4f80-935a-0755a66c2824)

![Captura de tela 2023-11-20 175411](https://github.com/melMass/comfy_mtb/assets/94875647/225c78f6-5a69-49aa-9c16-c85cca2a5ded)

### Operating System

Linux

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

**Comment by melMass** [comment]
Hi,

Thanks for the report, yes I actually removed them from the "setup" because they were a pain to maintain on windows (became impossible without using other approaches with Py11 afaik).

But other OSes work actually fine so I need to add instructions to properly install them. I personally still use all the optional nodes on windows and macos.

**Comment by melMass** [comment]
I will write better instructions did not have the time yet tbh.

That said I really recommend the alternatives listed in the readme as they are more up to date!
