### ISSUE TITLE
[bug] Tensorflow GPU not available, falling back to CPU this will be very slow

### ISSUE THREAD

**Issue by drago87** [melMass/comfy_mtb#137]
### Describe the bug

When using the Film Interpolation node with the VGG (only one tested for now) i get a `[comfy_mtb] | WARNING -> Tensorflow GPU not available, falling back to CPU this will be very slow` error in the cmd window and it takes forever to run.
I have a RTX 4080 ti 16gb

### Reproduction

![chrome_dykiQsh0rZ](https://github.com/melMass/comfy_mtb/assets/6805712/d35801eb-557c-40c3-be39-f4883dcb5436)
![chrome_4HPUwE35xy](https://github.com/melMass/comfy_mtb/assets/6805712/c35590c3-1d19-43b1-8c2f-88b2bdfa056a)

### Expected behavior

Using the GPU instead of the CPU

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
[comfy_mtb] | INFO -> Loading model D:\AI\ComfyUI_windows_portable\ComfyUI\models\FILM\VGG\saved_model
[comfy_mtb] | WARNING -> Tensorflow GPU not available, falling back to CPU this will be very slow
  2%|█▏                                                             | 8/435 [00:42<36:13,  5.09s/it]FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
 34%|█████████████████████                                        | 150/435 [12:43<23:55,  5.04s/it]
```

**Comment by drago87** [comment]
Got a new error randomly
```
[comfy_mtb] | INFO -> Loading model D:\AI\ComfyUI_windows_portable\ComfyUI\models\FILM\VGG\saved_model
2023-12-26 02:38:53.939534: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

**Comment by melMass** [comment]
Hi,
Thanks for the report, 
On windows this is a known issue, because most of the issues in this repo were about this I dropped support for TF based nodes on windows (FILM is one) ([more info](https://github.com/melMass/comfy_mtb#optional-nodes)), they also all have alternatives now. 

For Frame interpolation you want to check these ones: https://github.com/Fannovel16/ComfyUI-Frame-Interpolation , it contains various implementation of common methods like FILM (most in pytorch IIRC)
