### ISSUE TITLE
[bug]  unable to remove error path

### ISSUE THREAD

**Issue by rafstahelin** [melMass/comfy_mtb#184]
### Describe the bug

I have upscale_models setup in my extra paths yaml. On start, I get error message that MTB is looking for the local comfy path. 

```
[comfy_mtb] | WARNING -> Found multiple match, we will pick the first E:\comfy_ui\ComfyUI_windows_portable\ComfyUI\models\upscale_models
['E:\\comfy_ui\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'E:\\\\studio Dropbox\\\\studio\\ai\\\\libs\\\\SD\\\\4upscalingmodels']
```

### Reproduction

unable to remove this error message

### Expected behavior

this should not be showing on console on start

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
[comfy_mtb] | WARNING -> Found multiple match, we will pick the first E:\comfy_ui\ComfyUI_windows_portable\ComfyUI\models\upscale_models
['E:\\comfy_ui\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'E:\\\\studio Dropbox\\\\studio\\ai\\\\libs\\\\SD\\\\4upscalingmodels']
```

**Comment by melMass** [comment]
This is just a warning but I should handle it differently. Thanks for the report

**Comment by rafstahelin** [comment]
Thanks

**Comment by melMass** [comment]
I changed it from a warning to an info! 
Thanks to #177 the warning should only appear once. I'm don't feel like it's a good idea to fully remove it as it helps debugging issues. 
Thanks to your report I changed the logic in 1edc2cd10de81297e7a895009d358813e79b70ba to pick the last instead of the first, since custom_model paths are added at the end.

What do you think?

**Comment by rafstahelin** [comment]
Thanks looking good now cheers
