### ISSUE TITLE
[Question] Images to vídeo

### ISSUE THREAD

**Issue by Zakkx** [melMass/comfy_mtb#20]
Hi. How do I turn a sequence of images into a video? Is there an extra node to connect to video output (photo below), I couldn't find anything to connect it to? And another question, can I automatically apply a reference to all the images in a folder? The Load Image Sequence node doesn't read all the photos, only reads the frame of the photo I put in. Thanks!
![001](https://github.com/melMass/comfy_mtb/assets/138450161/ecd16a42-85e0-4cb2-96ef-2328687df920)
![002](https://github.com/melMass/comfy_mtb/assets/138450161/26c87767-a316-454f-9841-41ce50dbad53)

**Comment by melMass** [comment]
To debug it can you plug an image preview instead of the prores?

The `VIDEO` output is not used yet (it just contains a string path to the video file), I was planning on adding a video player widget but it's not done yet, for now the video is saved to Comfy's output dir using a random uuid to avoid overwriting previous ones.

The node doesn't load batches yet it uses the current frame input to select which to act on, but your issue makes me think I could add that easily. 

I'm currently working on a lot of frontend things in a private branch that focuses on animation/video

For instance animation builder, that uses the queue to increment various values, useful for animating all kind of things
![anim_glasses](https://github.com/melMass/comfy_mtb/assets/7041726/5117ec4f-30b8-4f1c-abda-f734a5012db9)

**Comment by Zakkx** [comment]
That's awesome! Seems pretty promising that animator you're working on. It looks like it's already in the final stages, huh? 
Regarding the batch node, maybe you could add a function with an asterisk sign so it understands that it should use all the photos in sequence from the folder to work on or something like that:
![0000](https://github.com/melMass/comfy_mtb/assets/138450161/7cca7512-22c4-4eb7-9655-75f213f8dd0e)
"To debug it can you plug an image preview instead of the prores?" Sorry, I didn't understand what you meant

**Comment by melMass** [comment]
I meant this just to check what comes out of load image sequence:


![image](https://github.com/melMass/comfy_mtb/assets/7041726/7b1b85bb-a766-43fc-bbe3-c5f638f1862d)

the idea is to load all frames if current_frame is -1 (not implemented in main yet it will be in #22) here 200 😅

**Comment by Zakkx** [comment]
Great news, thanks! I guess I'll need to be careful not to preview my folder or I'll blow up the memory of the google colab haha

**Comment by Zakkx** [comment]
Hello, any ETA on the next release? Thanks!
