### ISSUE TITLE
[bug] Several Nodes will not install

### ISSUE THREAD

**Issue by AIMusicExperiment** [melMass/comfy_mtb#52]
### Describe the bug

![image](https://github.com/melMass/comfy_mtb/assets/133187055/18ba6c7d-cb65-48d6-b2a3-929ec14c12eb)
As always thanks for you great nodes! Sadly I'm having trouble getting several of them to install. 
They are: 
Face Swap,
Face Enhance,
Mask,
Image Interpolation
Fun

I have tried installation through Manager in CompyUI as well a with git clone in CMD. I've run the install bats, basically I've done everything that I know to do. 

I really need to use Face swap for a project that I'm working on, so any help would be awesome!

 see attached output

### Reproduction

1. Click on install in Custom Nodes in Manager 
2. Restart ComfyUI
3. Read the error message, scream swear and cry.
4. Delete the folder and do a "git clone" from the MTB github
5. Restart ComfyUI and get the same error message
6. Do a "git pull" and get the "up to date" response
7. try the exact set of steps on your other installation of ComfyUI 
8. Have the same results, and decide that it is a bug.
9. Make a bug report and hope that it will get answered.

### Expected behavior

Ummm that the nodes would install and load.

### Platform and versions

```sh
-Windows 10
-ComfyUIBackend on Stable Swarm, but same issue on ComfyUI portable
-Everything is updated to current version as of right now.
```

### Additional context

I really Love you nodes! At least the ones that I can get to work.  Please offer some instruction for you suite! Also I am a YouTube creator, if you will help me get these figured out I will happily post tutorials! -Ava

**Comment by melMass** [comment]
Hi, 

Thanks again for the report and the kind words, 
If you can check and provide the log of the install it should help a lot, I tried to give meaningful feedback to what the issues might be.

That being said, the install script also has a "CLI" mode with arguments:
```sh
/path/to/comfy_embedded/python.exe ComfyUI/custom_nodes/comfy_mtb/install.py --help

usage: install.py [-h] [--path PATH] [--wheels] [--requirements] [--dry]

Comfy_mtb install script

options:
  -h, --help            show this help message and exit
  --path PATH, -p PATH  Path to clone the repository to (i.e the absolute path to ComfyUI/custom_nodes)
  --wheels, -w          Install wheel dependencies
  --requirements, -r    Install requirements.txt
  --dry                 Print what will happen without doing it (still making requests to the GH Api)
  ```

If this doesn't sound too complex you can try the following:
```sh
/path/to/comfy_embedded/python.exe ComfyUI/custom_nodes/comfy_mtb/install.py -w
```

**Comment by AIMusicExperiment** [comment]
I tried but just had cmd tell me that it couldn't find the path. . .Between a rock and hard place, because I don't want to lose the node that I have in order to get the ones I need. Is there an easier way to fix this?

**Comment by GoldmanOz** [comment]
I'm also having issues with nodes not installing, have installed through Comfy manager, and git pulled, everything telling me all is good until I try to load the face swap .json file then I'm getting the dreaded red nodes, won't update through the missing nodes function on the manager... I'm on an M1 MacBook Pro..  ????

**Comment by melMass** [comment]
Can you provide the log of the install steps? I fully tested mtb on my m1 but not through comfy-manager

**Comment by EricRollei** [comment]
Hi Mel, I'm also having trouble getting all the nodes to install.  I'm using the latest nightly windows portable build, have taken your previous advice and downloaded pyenv and created a local env for ComfyUI and installed Python 3.11 for that.    Here's my console output:

Log level: 20
RestoreFace
LoadFaceEnhanceModel
FaceSwap
LoadFaceSwapModel
LoadFaceAnalysisModel
QrCode
UnsplashImage
LoadFilmModel
FilmInterpolation
ConcatImages
GetBatchFromHistory
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import module faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import module fun because ModuleNotFoundError: No module named 'qrcode'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

I've got some of these modules in previous installs of mtb nodes in other folders....  but I'll try using your install commands. 
 
Do I need to delete the mtb folder in the ComfyUI/web/extensions/ folder for updates and re-installs?

**Comment by EricRollei** [comment]
ps if I run the install.py with -w --dry this is what I get in the console


A:\Comfy_Aug> A:/Comfy_Aug/python_embeded/python.exe A:/Comfy_Aug/ComfyUI/custom_nodes/comfy_mtb/install.py -w --dry
[mtb install] Detected environment: embeded
[mtb install] Downloading and installing release wheels since we are in a Comfy embeded environment
                ✅ Package onnxruntime-gpu already installed (import name: 'onnxruntime').
                ⛔ Package qrcode is missing (import name: 'qrcode').
                ✅ Package rembg already installed (import name: 'rembg').
                ⛔ Package tensorflow is missing (import name: 'tensorflow').
                ⛔ Package tb-nightly is missing (import name: 'tensorboard').
                ⛔ Package tensorflow is missing (import name: 'tensorflow').
                ⛔ Package facexlib is missing (import name: 'facexlib').
                ⛔ Package insightface is missing (import name: 'insightface').
                ⛔ Package basicsr is missing (import name: 'basicsr').
[mtb install] ⚙️ Sorting the release wheels using wheels order
[mtb install] Would have run the following command:
        A:\Comfy_Aug\python_embeded\python.exe -m pip install

I'm kind of scared to do it because this is how my comfy usually gets broken - the dependencies and stuff.  Let me back it up first, then I'll try it for real.

**Comment by EricRollei** [comment]
Okay here's the console when I run that install.py command for real and I think explains the issue:

A:\Comfy_Aug> A:/Comfy_Aug/python_embeded/python.exe A:/Comfy_Aug/ComfyUI/custom_nodes/comfy_mtb/install.py -w
[mtb install] Detected environment: embeded
[mtb install] Downloading and installing release wheels since we are in a Comfy embeded environment
                ✅ Package onnxruntime-gpu already installed (import name: 'onnxruntime').
                ⛔ Package qrcode is missing (import name: 'qrcode').
                ✅ Package rembg already installed (import name: 'rembg').
                ⛔ Package tensorflow is missing (import name: 'tensorflow').
                ⛔ Package tb-nightly is missing (import name: 'tensorboard').
                ⛔ Package tensorflow is missing (import name: 'tensorflow').
                ⛔ Package facexlib is missing (import name: 'facexlib').
                ⛔ Package insightface is missing (import name: 'insightface').
                ⛔ Package basicsr is missing (import name: 'basicsr').
[mtb install] ⚙️ Sorting the release wheels using wheels order
ERROR: pycocotools-2.0.6-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
Command failed with return code: 1
Ignoring tensorflow: markers 'platform_system != "Windows"' don't match your environment
Collecting onnxruntime-gpu==1.15.1 (from -r A:/Comfy_Aug/ComfyUI/custom_nodes/comfy_mtb/reqs.txt (line 1))
Obtaining dependency information for onnxruntime-gpu==1.15.1 from https://files.pythonhosted.org/packages/88/07/19f9ad96b9f3540883ae14276b98e2785b93ed40ba7247e682c98422af4a/onnxruntime_gpu-1.15.1-cp311-cp311-win_amd64.whl.metadata
Using cached onnxruntime_gpu-1.15.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting qrcode[pil] (from -r A:/Comfy_Aug/ComfyUI/custom_nodes/comfy_mtb/reqs.txt (line 2))
Using cached qrcode-7.4.2-py3-none-any.whl (46 kB)
Requirement already satisfied: rembg==2.0.50 in a:\comfy_aug\python_embeded\lib\site-packages (from -r A:/Comfy_Aug/ComfyUI/custom_nodes/comfy_mtb/reqs.txt (line 3)) (2.0.50)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0)
ERROR: No matching distribution found for tensorflow==2.10.1
Command failed with return code: 1
[mtb install] ✅ Successfully installed all dependencies.

**Comment by AIMusicExperiment** [comment]
Hi again, I see that my problem isn't in isolation. Can you update as to whether you have found a solution?  Your nodes that are working for me are SO GOOD, I'm pretty sure that the ones I can't get to install wood be super helpful. Please advise.

**Comment by melMass** [comment]
Hi everyone subscribed to this issue. Please open dedicated issues, you all have different cases...

@EricRollei 3.11 is not compatible with the tf version required as you can see in the log. Besides that the install went as expected

**Comment by GrafiTom** [comment]
> ./python_embeded/python.exe ComfyUI/custom_nodes/comfy_mtb/install.py -w

It helped me to clear up 3 of the 4 missing modules. I only have one left.
![hm4](https://github.com/melMass/comfy_mtb/assets/39159986/58bb9a5f-c13c-483c-be35-e9b3fd1875d5)

**Comment by GrafiTom** [comment]
and still...
![hm2](https://github.com/melMass/comfy_mtb/assets/39159986/717db26e-2574-425f-8c7a-9582754c723d)

**Comment by AIMusicExperiment** [comment]
Okay things are just getting worse for me.  It is probably my fault, but in spite  of spending hours on the (which frankly I don't have) I can not get this to work. It is likely that I just don't have the level of command line expertise that is necessary, but I can't make that  ./python_embeded/python.exe ComfyUI/custom_nodes/comfy_mtb/scripts/download_models.py -y thing that is working for others do anything. If I execute that command  cmd says that the path or file can't be found. Perhaps I need more instruction. 
I saw that you updated the commit since yesterday, so I deleted and reinstalled through manager and also from a "git clone" with either method the new repository, the extension completely breaks CompyUi. :( 

Compy UI opens, and if I load the default workflow, all the nodes are in red, and the manager is gone. As soon as I delete the MTB folder and restart everything else works fine. 

I love and need your nodes, but I have spent so much time down this rabbit hole that I just can't anymore.

You have asked for logs, but they are alll the same as the first one I posted.  Thanks for you help!

**Comment by melMass** [comment]
@AIMusicExperiment 
Those are both file paths: `./python_embeded/python.exe` & `ComfyUI/custom_nodes/comfy_mtb/scripts/download_models.py`, just find them on disk (the first is your ComfyPortable python.exe) the second this file https://github.com/melMass/comfy_mtb/blob/main/scripts/download_models.py that should be where I pointed you but it depends from where you are running it, you can use absolute paths.

You can also just find those path on disk and drag and drop them to the terminal, I personally use the [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701), but I think you can too in the basic cmd version.

**Comment by GrafiTom** [comment]
Any idea about my issue? My only error left is the tensorflow module..
everything installed the hard way :)

![hm1](https://github.com/melMass/comfy_mtb/assets/39159986/2093eaea-b822-4e14-b5eb-f72b529499d4)

**Comment by melMass** [comment]
@GrafiTom `Detected environment: unknown` is definitely the issue!

Are you using comfy portable? 

If so please provide the full path to the python executable although looking at the picture it seems you are probably mixing python environments :/

**Comment by GrafiTom** [comment]
Thanks for your answer.  Yeah, I guess that can be the problem. I am total noob to programming. I am running portable Comfy UI and everything works great. But the I wanted to check out mtb nodes and fell into the rabbit hole. :)So portable version uses its own embeded python? and it conflicts with the python installed on my system? What should I try?On 2023. Aug 8., at 22:53, Mel Massadian ***@***.***> wrote:﻿
@GrafiTom Detected environment: unknown is definitely the issue!
Are you using comfy portable?
If so please provide the full path to the python executable although looking at the picture it seems you are probably mixing python environments :/

**Comment by melMass** [comment]
> So portable version uses its own embeded python?

yes, the path should look something like `ComfyPortable/python-embeded/python.exe` and you want to use this to install dependencies in the portable version, there you installed them in your "global" system python

**Comment by GrafiTom** [comment]
Okay thanks! Will try that in the morning.  On 2023. Aug 8., at 23:30, Mel Massadian ***@***.***> wrote:﻿

So portable version uses its own embeded python?

yes, the path should look something like ComfyPortable/python-embeded/python.exe and you want to use this to install dependencies in the portable version, there you installed them in your "global" system python

**Comment by AIMusicExperiment** [comment]
I will now be slashing my veins, so feel free to read my obituary. . . in spite of vowing that I wasn't going to mess with this any more, I did a new install from a git clone using the parameters that you discussed, and I  also installed the models again using the parameters that you discussed. The install log said that all dependencies were successfully installed, and all the modals said that they correctly installed.

when I started ComfyUI the log showed the exact crap that I've been looking at for days now. 

When I opened the GUI ComfyUI was completely broken.  The only way to make it work is to remove you folder. This has become a complete nightmare, now I cannot only not us the nodes in question, but I can't use any of your nodes.

This has basically fucked my world, as I'm working on a workflow that uses a bunch of your other nodes and they don't work either.   Frankly, I should have just been happy and not tried to swap faces.  So lifes a bitch!

**Comment by AIMusicExperiment** [comment]
Thanks for abandoning us!

**Comment by melMass** [comment]
I'm seriously going to loose patience with this kind of attitude... you don't feel like I'm trying to help? 
I explained a point completely ignored here: https://github.com/melMass/comfy_mtb/issues/52#issuecomment-1669216274

**Comment by GrafiTom** [comment]
This is just basic attitude nowadays. :(
People feel that they deserve support for a free, experimental code.

Btw thanks for clearing up yesterday that embeded problem. I made a big
step forward.
Now every module loads fine, I can use examples 2,3,4

The only thing left is faceswap.. that missing nodes

**Comment by melMass** [comment]
Thanks yes it's just frustrating when you dedicate time and are thanked like that 😅


> The only thing left is faceswap.. that missing nodes


Can you open an issue? I think I found the remaining issues about install and will fix it in the next release, trackable at #50

**Comment by GrafiTom** [comment]
Well I just messed up something, and Comfy won't even start.. so made a
fresh install.
Now I am with a basic working ComfyUI portable.

Which way is the recommended? :)
Run the commands manually from python_embeded folder?

**Comment by AIMusicExperiment** [comment]
Mel, I have been nothing but complimentary to you, I simply expressed that I was frustrated that I couldn't get the app to work.  You have indeed offered a lot of help, but I have not been able to make your guidance work, When I finally had what looked like success, the entire comphy failed.  If you reread my earlier comment, you will see that it had nothing to do with you. I was doubly frustrated when I saw that you simply closed the issue, rather than responding. I think if you reread my comments here and also on the previous conversation you will remember that I have been very complimentary of you and your work. As we have discussed earlier, I am a YouTube content creator and I am working on a video that highlights your nodes for animation. 

Your level expertise can make it difficult for you to understand that regular users like myself don't have any idea what a python embedded environment is, or how that is affecting the install process. Many don't even understand how to use the command prompt, and have never heard of window shell. Not understanding your advice is not ignoring your advice. My experience with other custom nodes is that I click install on the manager and then when I restart CompyUI it works. I think that many others are of that mindset. Bottom line, my frustration is not and should not be seen as a reflection on you . 

GraphiTom, this is none of your fucking business! You jumped on to my issue and though welcomed, did nothing to help. I will not be judged by you as you have no understanding of me, my position, nor my background. I don't have the attitude of entitlement, but I do need for these nodes to work in order to do my work. It is immaterial as to the cost of the software, as I and my colleagues routinely compensate developers through Patreon, or "buy me a coffee."  My best advice to you is to mind your own business.   BTW I love that Karma stepped in and broke you app!

**Comment by GrafiTom** [comment]
Your last comment was really *misunderstandable*. Not only by me but be the
OP too.

I was forming a general opinion what I experience lately online. I had a
guy asking for help on discord,
I helped him in video editing, then next day he came for more, asking to do
it form him. etc. Then was totally angry when I told him he should educate
on the matter and try it on his own.

If you are the exception then *I apologise*. You have to admit that your
comment was weird. Maybe a smiley next time helps.

Loving that my app broke is interesting approach too.
Hope you will work out with mtb nodes and can progress with your work.
#Mel keep up the good work!  Have a nice day guys!

**Comment by melMass** [comment]
@AIMusicExperiment 

> Bottom line, my frustration is not and should not be seen as a reflection on you .

I might have overreacted because of previous similar behavior and frustration from my side and I woke up to your comment.
That said the main reason I closed this issue is the title being so generic 5 different users commented here instead of opening an issue, while the end result was mostly the same: some nodes won't install. Dealing with all those cases in the same thread is much more complicated, ideally 1 issue = 1 case, unless it's specific enough.


> Your level expertise can make it difficult for you to understand that regular users like myself don't have any idea what a python embedded environment is, or how that is affecting the install process.

I can definitely understand that my perspective is not always the best but I try to clarify as much as possible, I'm definitely not perfect at it and the dependencies needed by some node are really not helping me 😅 

> My experience with other custom nodes is that I click install on the manager and then when I restart CompyUI it works.

That's definitely the end goal and being an "early" adopter means you are seing this getting into shape (this phase took more thought and time than I initially expected), I did get some valuable info from the cases explained here in the end that I will implement in #50. I'm currently simplyfing a lot the install process and adding utilities to download dependencies and model from the UI directly:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/30542ac8-e07f-4252-ae4b-e415998f1606)

**Comment by melMass** [comment]
I should finish this today or tomorrow max. I just need a better testing suite

**Comment by EricRollei** [comment]
Hi Mel,
I didn't comment further since you identified that my install went ok other than the parts which aren't compatible with Python 3.11
I hope it's ok to make one post just to say I'm really thankful for your work here with these nodes. If I do another comfy install, what's the highest version of Python that is compatible with your nodes?

**Comment by melMass** [comment]
> I didn't comment further since you identified that my install went ok 

If you have further issues don't hesitate to open a new issue anytime! I would just wait for 0.1.4 since it should clear up an issue specific to windows embedded mode.

> If I do another comfy install, what's the highest version of Python that is compatible with your nodes?

On linux and mac any version of python that is compatible with Comfy, on windows any 3.10.X, On windows I personally use a shared virtualenv for A1111 & Comfy on python 3.10.11, on my mac m1 python 3.11.
Another option I'm thinking of doing is ship tensorflow cpu by default (since we can use the latest on windows too) and optionally add a way to install the gpu one (that requires an older tensorflow on windows), the main reason being the FILM interpolation nodes that are REALLY slow on CPU (like several minutes) and REALLY fast on GPU (like a few seconds)
