### ISSUE TITLE
[bug] Various errors

### ISSUE THREAD

**Issue by s-marcelle** [melMass/comfy_mtb#72]
### Describe the bug

Everything else works fine! I have all the neccessary models already downloaded. Below 

[comfy_mtb] | WARNING -> Web extensions folder at C:\Users\sherw\ComfyUI_\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import module faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'
        Failed to import module mask because ModuleNotFoundError: No module named 'numba'

### Platform and versions

```sh
Note: I am running the standalone version of Comfy
```

**Comment by melMass** [comment]
1. The first message simply tells you that when you are updating mtb the web modules will not automatically update since the install script failed to alias it. You can manually create a symlink (or just copy) `C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\comfy_mtb\extensions\mtb` 
 to `C:\Users\sherw\ComfyUI_\ComfyUI\web\extensions\mtb` , there is a rouch overview of what that means here [web readme](https://github.com/melMass/comfy_mtb/blob/main/web/README.md), but some node's UI will not work properly without the web modules.

2. For the second part, this is the same as #58 #49 #43 or many others. I still have no idea why the install fails for some people as I test it on isolated envs, one being a [CI here on github](https://github.com/melMass/comfy_mtb/actions/workflows/test_embedded.yml), two locally (windows and mac) and one on Google Colab

Can both logs from `C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\ComfyUI-Manager\`, there should be `comfyui.log` and `comfyui.prev.log`

**Comment by melMass** [comment]
Any update?

**Comment by s-marcelle** [comment]
Will do as soon as possible and notify of it. Going to give the steps outlined a try,

**Comment by s-marcelle** [comment]
I followed the first part and got the same error :

`[comfy_mtb] | WARNING -> Web extensions folder at C:\Users\sherw\ComfyUI_\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import module faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'
        Failed to import module mask because ModuleNotFoundError: No module named 'numba'`

As for the Manager Log.. Neither of those exists in the node folder...

:(

**Comment by s-marcelle** [comment]
I also added the /mtb at the end my comfyui url. I tried to install the deps from the status window and got this error:

`Error handling request
Traceback (most recent call last):
  File "C:\Users\sherw\ComfyUI_\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\sherw\ComfyUI_\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\sherw\ComfyUI_\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Users\sherw\ComfyUI_\ComfyUI\server.py", line 43, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 310, in do_action
    return await endpoint.do_action(request)
  File "C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 63, in do_action
    result = method(args) if args else method()
  File "C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 19, in ACTIONS_installDependency
    reqs = list(requirements.parse((here / "reqs_portable.txt").read_text()))
  File "pathlib.py", line 1134, in read_text
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sherw\\ComfyUI_\\ComfyUI\\custom_nodes\\comfy_mtb\\reqs_portable.txt'
`

**Comment by melMass** [comment]
closed by: https://github.com/melMass/comfy_mtb/commit/5dfea51dd8db2a4829e559eadeda22374b51c8a4
