### ISSUE TITLE
Please separate your modules into different packages [feat] 

### ISSUE THREAD

**Issue by AIMusicExperiment** [melMass/comfy_mtb#96]
### Describe the problem

The dependencies for some of your modules interfere with other nodes that I use.  That being said I really love your animation nodes. Is there anyway that you could divide this up so that I can use the nodes that are good and not have the ones that won't load and break everyone else's nodes? 

### Describe the solution you'd like

I write custome workflows that use your nodes, put people get angry with me because if they load your package, it brakes all the other facesap nodes, and your faceswap doesn't work for them. 

### Alternatives considered

I have considered using loopchain instead but, the save paths and such are really weird, Your animation builder is great! But it is useless to me if people won't use my workflows because I use your nodes.

**Comment by melMass** [comment]
Yep, the idea is not to split but have true optional nodes as in they don't install their dependencies by default.
This will be the case for the most problematic ones: FaceSwap, FaceRestore and FILM (from the top of my head).

This will avoid a lot of the issues and now I clearly redirect to other nodes for the face stuff since it's not a main focus but was more an early experiment I kept iterating on.

**Comment by melMass** [comment]
closed by: https://github.com/melMass/comfy_mtb/commit/5dfea51dd8db2a4829e559eadeda22374b51c8a4
